= Musashi

== Setting up the bot
Clone this repositery:

----
git clone https://github.com/scriptkitties/musashi.git
cd musashi
----

Copy the `files/musashi.toml` configuration file to any of the accepted
configuration locations:

- `/etc/musashi.conf`
- `/usr/local/etc/musashi.conf`
- `${XDG_CONFIG_HOME}/musashi.conf`
- `${HOME}/.config/musashi.conf`

These locations are scanned in order, the later ones overriding the keys set in
files loaded before it.

Next, install all dependencies using `zef`:

----
zef install --deps-only .
----

Finally, run the bot:

----
perl6 -Ilib bin/musashi.p6
----

=== Autostarting
In order to automatically start the bot, you should use your OS' service
management system.

==== FreeBSD
Copy `files/musashi.rc` to `/usr/local/etc/rc.d/musashi` and set
`musashi_enable="YES"` in your `rc.conf`. You can use the following parameters
to configure Musashi:

- `musashi_user`: The user Musashi will run as. Defaults to `musashi`.
- `musashi_directory`: The directory to the local Musashi repository. Defaults
  to `/srv/bots/musashi`.
- `musashi_perl6`: Path to the Perl 6 interpreter. Defaults to
  `/usr/local/bin/perl6`.
- `musashi_log`: Directory to store `musashi.log` and `musashi.err` in.
  Defaults to `$musashi_directory`.
- `musashi_pidfile`: Path to store a pidfile for Musashi. Defaults to
  `/var/run/musashi.pid`. If you change this, be sure to change it to the same
  value in the `musashi.toml` configuration file.

== License
This software is distributed under the GPLv3.
